### ISSUE TITLE
blob.js and filesaver.js from NPM

### ISSUE THREAD

**Issue by thomas3577** [alferov/angular-file-saver#10]
Can you update your package.json and get blob.js and filesaver.js from NPM?

**Comment by alferov** [comment]
These npm packages are not well-maintained. That's why I've decided to fork it and get it from github directly (https://github.com/alferov/angular-file-saver/blob/master/package.json#L24-L25). There is no sense to publish it on npm (since there are no official releases).

**Comment by wips** [comment]
Your approach makes it impossible to use your package on systems where git is unavailable - i. e. our CI server. Could you consider once more using npm package instead of git, please (i.e. `https://www.npmjs.com/package/cf-blob.js`)?

**Comment by luigisworld** [comment]
I'm completely agree with @wips. Please consider using npm, it is absolutely necessary. Thx

**Comment by chesminsky** [comment]
+1  please remove git dependency

**Comment by AlexBsrd** [comment]
Hello,
Sorry to unearth the subject but I spent the whole day trying to resolve this error on an Azure pipeline and it would have been impossible without this thread.
Apparently the creator does not maintain this directory so for those like me who would need this functionality, replace the dependency "angular-file-saver" in your package.json with "file-saver": "2.0.2" ([npm](https://www.npmjs.com/package/file-saver))
This dependency uses the same syntax so it may have no impact on your existing 

Hoping this will help you as much as it does for me :)
