### ISSUE TITLE
Export angular-file-saver as CommonJS-module

### ISSUE THREAD

**Issue by brunnurs** [alferov/angular-file-saver#11]
It would be great if we could include angular-file-saver with the [CommonJS modularization-syntax](http://wiki.commonjs.org/wiki/Modules/1.1#Module_Context). Using your great piece of code, especially in combination with NPM, browserify and AngularJS, would be much simpler.

As an example, have a look at my angular app.js file:

```javascript
var app = angular.module('myProject', [
    'cgBusy',
    'ngFileSaver',
    'ngmap',
    require('angular-ui-router'),
    require('angular-animate'),
    require('angular-resource'),
    require('angular-ui-bootstrap'),
    require('ng-file-upload'),
    require('angular-smart-table'),
    require('angular-cookies'),
    require('angular-translate'),
    require('angular-dynamic-locale')
```

Most of my 3rd party dependencies (except of the first three) are referenced with the CommonJS `require` - keyword. With [browserify](http://browserify.org/), all I need to do is to execute `browserify app.js > bundle.js` and all dependencies (and even more important the transitive dependencies) are loaded from NPM in the specified version and bundled to one file. No need to add the files to my `index.html` manually or with additional tools like Grunt/Gulp. All we need to do is the standard angular initialization.

AFAIK, it is quite easy to implement it. Add an `index.js`- file with the following content to your repo (example is the angular-animate dependency):

```javascript
require('./angular-animate');
module.exports = 'ngAnimate';
```

It is also an investment into the future, as the  [module-concept ](http://www.infoq.com/news/2014/09/ecmascript6) will be an important part of ECMAScript 6.

Let me know if I can help u!

**Comment by evoker** [comment]
Hi, how did you get this to work with browserify? I'm having a hard time getting to work.

Any tips?

**Comment by brunnurs** [comment]
AFAIK you can't browsify a dependency if it doesn't support the CommonJS-standard (or at least a "light" version of it). It still include the angular-file-saver without browsify. If you have time, you might implement a PR to support this feature. I will implement it for another repo (https://github.com/allenhwkim/angularjs-google-maps) so maybe if it's an easy task, i might also implement a PR for this repo. But not sure yet, as a little low on time :-)

**Comment by alferov** [comment]
Sorry for the delay guys.
This project does support CommonJS as it's being exported as a CommonJS module:
https://github.com/alferov/angular-file-saver/blob/master/dist/angular-file-saver.bundle.js#L1

@brunnurs, @evoker, Do you use Windows?

**Comment by evoker** [comment]
@alferov Yes, currently on a windows machine.

**Comment by brunnurs** [comment]
@alferov You are absolutely right, the project supports CommonJS and Browserify is also able to include your project. The missing piece is the line:
`	module.exports = 'ngFileSaver';`
which enables angular to add your project as module- dependency (see my code above). I will create a PR with the update.
With this small improvements, it works for me like a charm.
