### ISSUE TITLE
angular-file-saver browserify

### ISSUE THREAD

**Issue by evoker** [alferov/angular-file-saver#12]
Hi,

I've been trying to import angular-file-saver via browserify but when I import \dist\angular-file-saver.js, I get the following error during the browserify task on grunt:

    Error: Cannot find module './angular-file-saver.service' from 'C:\blah\bower_components\angular-file-saver\dist'

I have also tried to use /src/angular-file-saver.module.js instead which passes the related grunt task but then when running the app I get this error:

    Error: saveAs is not supported. Please include saveAs polyfill

I have followed the docs (it's quite simple anyway) to the letter, but no luck.

Any thoughts?

Thanks in advance!

**Comment by alferov** [comment]
Hey, have you tried to install it with npm?

**Comment by brunnurs** [comment]
@evoker I had the same error when trying to import the module with the following code:
```javascript  
require('angular-file-saver/dist/angular-file-saver.js')
```
The point is you just import (or require) `require('angular-file-saver')`. Browserify will look up the path _angular-file-saver_ in the NPM-modules and look for a _package.json_ where, the _main_-field points to the actual js-file. 

```json  
"main": "src/angular-file-saver-bundle.module.js",
```
This way, angular-file-saver with browserify works for me.

**Comment by alferov** [comment]
Fixed in https://github.com/alferov/angular-file-saver/releases/tag/1.1.0
