### ISSUE TITLE
How to save a pdf blob content

### ISSUE THREAD

**Issue by vinay07-gl** [alferov/angular-file-saver#24]
How to save a pdf blob content. I am using type: application/pdf, but wrong format gets downloaded. The blob works well with older approaches like : window.URL.createObjectURL(blob) or window.navigator.msSaveOrOpenBlob(blob, fileName)

**Comment by feitzi** [comment]
same problem here, what was your solution?

**Comment by vinay07-gl** [comment]
@feitzi Use below code:
req.onload = function (event, header) {
              var blob = req.response;
              try{
                  window.navigator.msSaveOrOpenBlob(blob, fileName);
              } 
              catch(ex){
                var data = new Blob([blob],{type:'application/octet-stream'});
                FileSaver.saveAs(data, fileName);
              }                           
          };
This will work on all the broswers. The only limitation on Mac Safari is that the file will get downloaded as "Unknown", and will have no extension. You will have to put the extension and give it some file name. And also update to the latest version of file saver.

**Comment by feitzi** [comment]
My problem was that i load the file from the server with a wrong responseType. 

Setting the responseType in httpService to arraybuffer and everything works smoothly.

>  httpService.get(this.scope.fileUrl, { responseType: "arraybuffer" })

**Comment by vinay07-gl** [comment]
@feitzi Awsome.
In my case I was expecting response type of any format i.e. pdf, zip, doc etc. So, req.responseType = "blob"; worked for me.
