### ISSUE TITLE
issue running with PhantomJS?

### ISSUE THREAD

**Issue by cstephe** [alferov/angular-file-saver#8]
loading angular-file-saver/dist/angular-file-saver.bundle.js
Seems to crash phantomJS

looking into it

**Comment by cstephe** [comment]
appears to be an issue with Phantom 1.9 and the blob polyfill.  Will update if 2.0 fixes this.

**Comment by alferov** [comment]
Hey @cstephe, any updates regarding this issue?

**Comment by cstephe** [comment]
2.0 fixes the issue when I installed it locally.  

However in my case I can't install 2.0 on our build server because of other stnd C lib dependencies needed to build it.   so I just changed my test to go around the need.  I loaded all the files for the module individually (non bundle) except the blob so that dependencies can be satisfied, then I just avoided testing code paths that need blob.  I only had one, one liner so it wasn't a deal breaker.
